[pm] feature: process abstraction
nanvix/multikernel pull request #240
Opened 2021-02-03 11:40 UTC by Nicolas-Vanz

Added basic process id and process group id management functionalities

2021-02-03 20:13 UTC, joaovicentesouto requested changes
The principle is ok but you replicate the "proc service" across the clusters, i.e., each cluster has your on proc and group tables but they must be store centralized on an IO cluster. In other words, the compute cluster must request that information from an IO cluster.

Let's make a call to discuss this.

2021-03-05 10:18 UTC, ppenna approved these changes

2021-03-05 10:18 UTC, ppenna commented on include/nanvix/servers/groups.h
> +	};
Why do we need a structure for this? What do you plan to include here in the future?

2021-03-05 10:18 UTC, ppenna commented on src/sys/pm/name/main.c
> +
Remove curly braces for single statements for loops and conditions.

2021-03-05 10:18 UTC, ppenna commented on src/sys/pm/name/main.c
> +
We should block a process to set its PID once it was set.

2021-03-05 10:18 UTC, ppenna commented on include/nanvix/limits/pm.h
> +
We don't need to limit the number of groups, only the number of processes in the system.

2021-04-22 18:24 UTC, Nicolas-Vanz commented on include/nanvix/servers/groups.h
> +	};
This structure was dropped in the newest commit. Now we identify groups by an integer.

2021-04-24 18:16 UTC, joaovicentesouto requested changes
I had a conversation with Pedro and we decide to change the type of the PID but this continues to store the same information about the process.

There is a lot of comment but most of them are about it. Let's make a meet to discuss them.

2021-04-24 18:16 UTC, joaovicentesouto commented on src/libruntime/pm/proc/proc.c
> +int server;
This is already defined in the common.c.

2021-04-24 18:16 UTC, joaovicentesouto commented on src/libruntime/pm/proc/proc.c
> +bool initialized;
This is already defined in the common.c.

2021-04-24 18:16 UTC, joaovicentesouto commented on src/libruntime/pm/proc/proc.c
> +struct proc_info proc_info;
This is already defined in the common.c.

2021-04-24 18:16 UTC, joaovicentesouto commented on src/libruntime/pm/proc/proc.c
> +	if (pid.source < PROCESSOR_CLUSTERS_NUM)
We should introduce a constant to define an invalid pid (`NANVIX_PID_NULL`)

2021-04-24 18:16 UTC, joaovicentesouto commented on src/libruntime/pm/proc/proc.c
> +struct pid nanvix_getpid(void)
Change to `nanvix_pid_t`

2021-04-24 18:16 UTC, joaovicentesouto commented on src/libruntime/pm/proc/proc.c
> +int nanvix_get_proc_nodenum(void)
Change the function name to `nanvix_proc_get_nodenum`

2021-04-24 18:16 UTC, joaovicentesouto commented on src/libruntime/pm/proc/proc.c
> +		if (proc_info.pid.source >= PROCESSOR_CLUSTERS_NUM)
We should introduce a constant to define an invalid pid (`NANVIX_PID_NULL`)

2021-04-24 18:16 UTC, joaovicentesouto commented on src/libruntime/pm/proc/proc.c
> +	if (msg.header.opcode == NAME_SUCCESS)
Move the error to this check.

2021-04-24 18:16 UTC, joaovicentesouto commented on src/libruntime/pm/proc/proc.c
> +		if (proc_info.pid.source >= PROCESSOR_CLUSTERS_NUM)
We should introduce a constant to define an invalid pid (`NANVIX_PID_NULL`)

2021-04-24 18:16 UTC, joaovicentesouto commented on src/libruntime/pm/proc/proc.c
> +	if (msg.header.opcode == NAME_SUCCESS)
Move the error to this verification.

2021-04-24 18:16 UTC, joaovicentesouto commented on src/sys/fs/vfs/main.c
> +	if (pid.source >= PROCESSOR_CLUSTERS_NUM)
We should introduce a constant to define an invalid pid (`NANVIX_PID_NULL`)

2021-04-24 18:16 UTC, joaovicentesouto commented on src/sys/mm/rmem/main.c
> +	if (pid.source >= PROCESSOR_CLUSTERS_NUM)
We should introduce a constant to define an invalid pid (`NANVIX_PID_NULL`)

2021-04-24 18:16 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +		procs[i].pid.source = PROCESSOR_CLUSTERS_NUM;
We should introduce a constant to define an invalid pid (`NANVIX_PID_NULL`)

2021-04-24 18:16 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +	response->op.ret.proc_info.pid.source = PROCESSOR_CLUSTERS_NUM;
We should introduce a constant to define an invalid pid (`NANVIX_PID_NULL`)

2021-04-24 18:16 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +	if (pid.source == PROCESSOR_CLUSTERS_NUM)
We should introduce a constant to define an invalid pid (`NANVIX_PID_NULL`)

2021-04-24 18:16 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +		if (procs[i].pid.source == PROCESSOR_CLUSTERS_NUM)
We should introduce a constant to define an invalid pid (`NANVIX_PID_NULL`)

2021-04-24 18:16 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +		if (procs[i].pid.source == PROCESSOR_CLUSTERS_NUM)
We should introduce a constant to define an invalid pid (`NANVIX_PID_NULL`)

2021-04-24 18:16 UTC, joaovicentesouto commented on src/sys/pm/sysv/main.c
> +	if (pid.source >= PROCESSOR_CLUSTERS_NUM)
We should introduce a constant to define an invalid pid (`NANVIX_PID_NULL`)

2021-04-24 18:16 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +	struct pid pid;
We must exchange `struct pid` to `nanvix_pid_t`. See the comment about the `struct pid`.

2021-05-21 14:19 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
>  	procs[0].nodenum  = knode_get_num();
We are creating a process here, is it missing to set up the PID to it? It can be the PID 1.

2021-05-21 14:24 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +	if ((nanvix_gid_t)pid != pgid)
Add a space between the cast and the variable.

2021-05-21 14:29 UTC, joaovicentesouto commented on src/ubin/test/name/api.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We already checked that the `pid` is valid on proc tests.
You can remove these assertations.

2021-05-21 14:29 UTC, joaovicentesouto commented on src/ubin/test/name/api.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We already checked that the `pid` is valid on proc tests.
You can remove these assertations.

2021-05-21 14:29 UTC, joaovicentesouto commented on src/ubin/test/name/api.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We already checked that the `pid` is valid on proc tests.
You can remove these assertations.

2021-05-21 14:30 UTC, joaovicentesouto commented on src/ubin/test/name/api.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We already checked that the `pid` is valid on proc tests.
You can remove these assertations.

2021-05-21 14:31 UTC, joaovicentesouto commented on src/ubin/test/name/fault.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We already checked that the `pid` is valid on proc tests.
You can remove these assertations.

2021-05-21 14:31 UTC, joaovicentesouto commented on src/ubin/test/name/fault.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We already checked that the `pid` is valid on proc tests.
You can remove these assertations.

2021-05-21 14:31 UTC, joaovicentesouto commented on src/ubin/test/name/fault.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We already checked that the `pid` is valid on proc tests.
You can remove these assertations.

2021-05-21 14:31 UTC, joaovicentesouto commented on src/ubin/test/name/stress.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We already checked that the `pid` is valid on proc tests.
You can remove these assertations.

2021-05-21 14:36 UTC, joaovicentesouto commented on src/ubin/test/proc/api.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We know where this process is running, so we can compare the source with `PROCESSOR_NODENUM_LEADER`.

Add two new assertions:
- Compare the source with the `knode_get_num()`
- Check if a second `nanvix_getpid()` return the same value of the `pid`.

2021-05-21 14:38 UTC, joaovicentesouto commented on src/ubin/test/proc/api.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We already checked that the `pid` is valid on the previous test.
You can remove these assertations.

2021-05-21 14:38 UTC, joaovicentesouto commented on src/ubin/test/proc/api.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We already checked that the `pid` is valid on the previous test.
You can remove these assertations.

2021-05-21 14:39 UTC, joaovicentesouto commented on src/ubin/test/proc/fault.c
> +	TEST_ASSERT(nanvix_pid_get_source(pid) < PROCESSOR_CLUSTERS_NUM);
We already checked that the `pid` is valid on API test.
You can remove these assertations.

2021-05-21 14:39 UTC, joaovicentesouto commented on src/ubin/test/proc/fault.c
> +}
Add a new line after this line.

2021-05-31 12:00 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +
@ppenna, could you clarify the context of this comment?

2021-05-31 12:52 UTC, joaovicentesouto requested changes
Just small changes, I think.

2021-05-31 12:52 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +	pid = nanvix_pid_set_id(pid, pid_counter++);
**Observation:** This makes the reserved field contains all bits equal to 1 because the default PID is NULL.
I think this is not a problem because all PIDs will have the same reserved value but we must be careful in the future. Maybe we just add a DEFAULT value if this becomes a problem.

2021-05-31 12:52 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +		if (procs[i].pid == pid)
The previous version looked for invalid nodenums:
```c
/* Found. */
if (procs[i].nodenum < 0)
...
```
And now you are looking for a valid PID? This is right? We mustn't look for a **free slot** here?

2021-05-31 12:52 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +	procs[index].pid = pid;
We must still keep the Nodenum of the process.

**This highlights an enhancement on the name server:** we must separate the process info from the mapping of the names. But, this is another PR.

2021-05-31 12:52 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
>  				procs[i].port_nr = -1;
Clear the nodenum and PID information.

2021-05-31 12:52 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +	name_debug("heartbeat pid=%d timestap=%l", pid, timestamp);
You can keep checking if the PID is valid.

2021-05-31 12:52 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +
This could be done in another PR with this enhancement/bugfix: Separate the process information from the mapping of the names.

2021-05-31 14:16 UTC, ppenna commented on src/sys/pm/name/main.c
> +
@joaovicentesouto I agree.

2021-05-31 15:31 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
> +
This is being done on the client side.

2021-06-02 13:34 UTC, joaovicentesouto commented on src/sys/pm/name/main.c
>  } procs[NANVIX_PNAME_MAX];
@ppenna, in this PR, we separate the process information from the name mapping because a process can have more than one name. So, what do you think about the number of processes compared with the number of possible names? We are using the same constant here (256).

2021-06-02 13:45 UTC, joaovicentesouto approved these changes

2021-06-06 13:13 UTC, merged